pipeline{
    agent any
        stages {
            stage ('install') {
                steps {
                    dir("proyecto-vue/tareas-vue"){
                        sh "npm install"
                    }
                }
            }
        
            stage ('build') {
                steps {
                    dir("proyecto-vue/tareas-vue"){
                        sh "npm run build"
                    }
                }
            }
            stage ('Test Sonar') {
                steps {
                    dir("proyecto-vue/tareas-vue/tests/unit"){
                        sh "npm run test:coverage"
                    }
                }
            }
            // stage ('Sonar') {
            //     steps {
            //         dir("proyecto-vue/tareas-vue"){
            //             sh "npm run sonar"
            //         }
            //     }
            // }        
        }
}